version: '3.3'
services:
  web:
    image: nginx:latest
    ports:
      - 80:80
    depends_on:
      - flutter
    volumes:
      - vol:/usr/share/nginx/html
    command: ["/usr/sbin/nginx", "-g", "daemon off;"]
  flutter:
    image: nimeshgarg/infs3208:latest
    volumes:
      - vol:/app/build/web

volumes:
  vol:
    