version: '3.7'
services:
  flutter:
    image: nimeshgarg/infs3208:latest
    volumes:
      - vol:/app/build/web
    deploy:
      placement:
        constraints: [node.role == manager]
        
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    depends_on:
      - flutter
    volumes:
      - vol:/usr/share/nginx/html
    deploy:
      mode: replicated
      replicas: 2
    command: ["/usr/sbin/nginx", "-g", "daemon off;"]

volumes:
  vol:
    